"""add rule title

Revision ID: 237d7066ab7c
Revises: 3f712b0d0e24
Create Date: 2026-09-08 00:47:08.236115

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "237d7066ab7c"
down_revision: str | Sequence[str] | None = "3f712b0d0e24"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("rules", sa.Column("title", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("rules", "title")
    # ### end Alembic commands ###
