"""add rule order_index

Revision ID: 2e516a760445
Revises: 237d7066ab7c
Create Date: 2026-09-08 01:08:03.534805

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e516a760445'
down_revision: Union[str, Sequence[str], None] = '237d7066ab7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        'rules', sa.Column('order_index', sa.Integer(), nullable=False, server_default='0')
    )
    # ### end Alembic commands ###

    # Backfill: order_index becomes the authoritative apply/replay/list
    # order (spec 008), replacing implicit id order (spec 005). Set each
    # existing rule's order_index to its rank by id within its table, so
    # behavior is unchanged for every rule that predates this migration.
    op.execute(
        """
        UPDATE rules
        SET order_index = (
            SELECT COUNT(*)
            FROM rules AS earlier
            WHERE earlier.decision_table_id = rules.decision_table_id
              AND earlier.id < rules.id
        )
        """
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rules', 'order_index')
    # ### end Alembic commands ###
