"""add rules and rule_values

Revision ID: 3f712b0d0e24
Revises: 4f8f62174024
Create Date: 2026-09-07 23:59:55.173035

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "3f712b0d0e24"
down_revision: str | Sequence[str] | None = "4f8f62174024"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "rules",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_table_id", sa.Integer(), nullable=False),
        sa.Column("output", sa.Text(), nullable=False),
        sa.Column("matched_count", sa.Integer(), nullable=False),
        sa.Column("applied_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_table_id"], ["decision_tables.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("ix_rules_table", "rules", ["decision_table_id"], unique=False)
    op.create_table(
        "rule_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("rule_id", sa.Integer(), nullable=False),
        sa.Column("factor_id", sa.Integer(), nullable=False),
        sa.Column("factor_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["factor_id"], ["factors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["factor_value_id"], ["factor_values.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["rule_id"], ["rules.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("rule_id", "factor_id", name="uq_rule_value_factor"),
    )
    op.create_index("ix_rule_values_rule", "rule_values", ["rule_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_rule_values_rule", table_name="rule_values")
    op.drop_table("rule_values")
    op.drop_index("ix_rules_table", table_name="rules")
    op.drop_table("rules")
    # ### end Alembic commands ###
