"""initial schema

Revision ID: 4f8f62174024
Revises:
Create Date: 2026-09-07 22:45:09.036614

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4f8f62174024"
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "decision_tables",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "factors",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_table_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_table_id"], ["decision_tables.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("decision_table_id", "name", name="uq_factor_table_name"),
    )
    op.create_table(
        "generation_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_table_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("total_combinations", sa.Integer(), nullable=False),
        sa.Column("created_count", sa.Integer(), nullable=False),
        sa.Column("cursor", sa.Integer(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_table_id"], ["decision_tables.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_generation_jobs_table_status",
        "generation_jobs",
        ["decision_table_id", "status"],
        unique=False,
    )
    op.create_table(
        "combinations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("decision_table_id", sa.Integer(), nullable=False),
        sa.Column("generation_job_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("output", sa.Text(), nullable=True),
        sa.Column("impossible_reason", sa.Text(), nullable=True),
        sa.Column("signature", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["decision_table_id"], ["decision_tables.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["generation_job_id"], ["generation_jobs.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "decision_table_id", "signature", name="uq_combination_signature"
        ),
    )
    op.create_index(
        "ix_combinations_table_status",
        "combinations",
        ["decision_table_id", "status"],
        unique=False,
    )
    op.create_table(
        "factor_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("factor_id", sa.Integer(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(["factor_id"], ["factors.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("factor_id", "value", name="uq_factor_value"),
    )
    op.create_table(
        "combination_values",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("combination_id", sa.Integer(), nullable=False),
        sa.Column("factor_id", sa.Integer(), nullable=False),
        sa.Column("factor_value_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["combination_id"], ["combinations.id"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["factor_id"], ["factors.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["factor_value_id"], ["factor_values.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "combination_id", "factor_id", name="uq_combination_value_factor"
        ),
    )
    op.create_index(
        "ix_combination_values_combination",
        "combination_values",
        ["combination_id"],
        unique=False,
    )
    op.create_index(
        "ix_combination_values_factor_value",
        "combination_values",
        ["factor_id", "factor_value_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_combination_values_factor_value", table_name="combination_values")
    op.drop_index("ix_combination_values_combination", table_name="combination_values")
    op.drop_table("combination_values")
    op.drop_table("factor_values")
    op.drop_index("ix_combinations_table_status", table_name="combinations")
    op.drop_table("combinations")
    op.drop_index("ix_generation_jobs_table_status", table_name="generation_jobs")
    op.drop_table("generation_jobs")
    op.drop_table("factors")
    op.drop_table("decision_tables")
    # ### end Alembic commands ###
